// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-server/src/main/proto/configuration.proto

/*
Package com_example_grpcserver is a generated protocol buffer package.

It is generated from these files:
	grpc-server/src/main/proto/configuration.proto

It has these top-level messages:
	UserCreateRequest
	UserCreateResponse
*/
package com_example_grpcserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserCreateRequest struct {
	Name    string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age     int32   `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Aadhaar int64   `protobuf:"varint,3,opt,name=aadhaar" json:"aadhaar,omitempty"`
	Salary  float64 `protobuf:"fixed64,4,opt,name=salary" json:"salary,omitempty"`
	IsDev   bool    `protobuf:"varint,5,opt,name=isDev" json:"isDev,omitempty"`
	Address string  `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
}

func (m *UserCreateRequest) Reset()                    { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()               {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserCreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserCreateRequest) GetAadhaar() int64 {
	if m != nil {
		return m.Aadhaar
	}
	return 0
}

func (m *UserCreateRequest) GetSalary() float64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

func (m *UserCreateRequest) GetIsDev() bool {
	if m != nil {
		return m.IsDev
	}
	return false
}

func (m *UserCreateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserCreateResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *UserCreateResponse) Reset()                    { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()               {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserCreateResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreateRequest)(nil), "com.example.grpcserver.UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "com.example.grpcserver.UserCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Create(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserCreateResponse, error) {
	out := new(UserCreateResponse)
	err := grpc.Invoke(ctx, "/com.example.grpcserver.User/create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Create(context.Context, *UserCreateRequest) (*UserCreateResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.example.grpcserver.User/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Create(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.example.grpcserver.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _User_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-server/src/main/proto/configuration.proto",
}

func init() { proto.RegisterFile("grpc-server/src/main/proto/configuration.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x4f, 0x4e, 0xeb, 0x30,
	0x10, 0x87, 0xe5, 0xfe, 0xc9, 0x7b, 0x78, 0x55, 0x2c, 0xa8, 0xac, 0xc2, 0x22, 0xca, 0x2a, 0x54,
	0x10, 0x0b, 0xd8, 0xb1, 0x04, 0x0e, 0x80, 0x2c, 0x71, 0x80, 0xc1, 0x1d, 0xd2, 0x48, 0x8d, 0x1d,
	0x3c, 0x6e, 0x04, 0x12, 0x2b, 0xc4, 0x0d, 0x58, 0x72, 0x2c, 0xae, 0xc0, 0x41, 0x50, 0x9d, 0x54,
	0x42, 0x82, 0x05, 0xbb, 0xf9, 0xac, 0xf9, 0xc6, 0xbf, 0x19, 0x5e, 0x94, 0xbe, 0x31, 0x27, 0x84,
	0xbe, 0x45, 0xaf, 0xc8, 0x1b, 0x55, 0x43, 0x65, 0x55, 0xe3, 0x5d, 0x70, 0xca, 0x38, 0x7b, 0x5f,
	0x95, 0x6b, 0x0f, 0xa1, 0x72, 0xb6, 0x88, 0x6f, 0x62, 0x6a, 0x5c, 0x5d, 0xe0, 0x23, 0xd4, 0xcd,
	0x0a, 0xa3, 0xdb, 0xa9, 0xb3, 0xc3, 0xd2, 0xb9, 0x72, 0x85, 0x0a, 0x9a, 0x4a, 0x81, 0xb5, 0x2e,
	0x44, 0x89, 0x3a, 0x2b, 0x7b, 0x67, 0x7c, 0xf7, 0x96, 0xd0, 0x5f, 0x79, 0x84, 0x80, 0x1a, 0x1f,
	0xd6, 0x48, 0x41, 0x08, 0x3e, 0xb2, 0x50, 0xa3, 0x64, 0x29, 0xcb, 0x77, 0x74, 0xac, 0xc5, 0x84,
	0x0f, 0xa1, 0x44, 0x39, 0x48, 0x59, 0x3e, 0xd6, 0x9b, 0x52, 0x48, 0xfe, 0x0f, 0x60, 0xb1, 0x04,
	0xf0, 0x72, 0x98, 0xb2, 0x7c, 0xa8, 0xb7, 0x28, 0xa6, 0x3c, 0x21, 0x58, 0x81, 0x7f, 0x92, 0xa3,
	0x94, 0xe5, 0x4c, 0xf7, 0x24, 0xf6, 0xf8, 0xb8, 0xa2, 0x6b, 0x6c, 0xe5, 0x38, 0x65, 0xf9, 0x7f,
	0xdd, 0x41, 0x9c, 0xb3, 0x58, 0x78, 0x24, 0x92, 0x49, 0xfc, 0x70, 0x8b, 0xd9, 0x31, 0x17, 0xdf,
	0xc3, 0x51, 0xe3, 0x2c, 0x61, 0x9c, 0x1e, 0x20, 0xac, 0xa9, 0xcf, 0xd7, 0xd3, 0xd9, 0x2b, 0xe3,
	0xa3, 0x4d, 0xbb, 0x78, 0xe6, 0x89, 0x89, 0x8a, 0x38, 0x2a, 0x7e, 0xbf, 0x4a, 0xf1, 0x63, 0xe7,
	0xd9, 0xfc, 0x2f, 0xad, 0x5d, 0x82, 0xec, 0xe0, 0xe5, 0xe3, 0xf3, 0x6d, 0xb0, 0x9f, 0x4d, 0x54,
	0x7b, 0xaa, 0x7a, 0x45, 0xa1, 0x59, 0xba, 0x0b, 0x36, 0xbf, 0x1c, 0xdc, 0xb0, 0xbb, 0x24, 0x5e,
	0xf7, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x34, 0x4d, 0xf1, 0x63, 0xc5, 0x01, 0x00, 0x00,
}
